version: '3'
services:
  frontend:
    build: ./frontend 
    image: ghcr.io/utscc09/frontend-vineet1610
    restart: always
    networks:
      - sub-etha
  backend:
    build: ./backend
    image: ghcr.io/utscc09/backend-vineet1610
    restart: always 
    networks:
      - sub-etha
  revproxy:
    build: ./nginx
    image: ghcr.io/utscc09/reverse-proxy-vineet1610
    networks:
      - sub-etha
    ports:
      - "80:80"
networks:
  sub-etha: