version: '3'
services:
  frontend:
    build: ./frontend 
    image: uoftsocials.azurecr.io/frontend
    restart: always
    networks:
      - sub-etha
  backend:
    build: ./backend
    image: uoftsocials.azurecr.io/backend
    restart: always 
    networks:
      - sub-etha
  revproxy:
    build: ./nginx
    image: "uoftsocials.azurecr.io/reverseproxy:1.0.0"
    networks:
      - sub-etha
    ports:
      - "80:80"
networks:
  sub-etha: